import type { CollectionsApiConfig } from "../types/config";

// 使用 favicon 服务获取网站图标
const favicon = (domain: string) => `https://favicon.im/${domain}`;

export const collectionsApiConfig: CollectionsApiConfig = {
	// 页面标题，留空则使用 i18n 翻译
	title: "",
	// 页面描述，留空则使用 i18n 翻译
	description: "",

	// API 收藏列表
	apis: [
		{
			name: "中科大测速",
			url: "https://test.ustc.edu.cn/",
			description: "中国科学技术大学网络测速，基于 LibreSpeed，支持 IPv4/IPv6",
			category: "测试数据",
			icon: favicon("test.ustc.edu.cn"),
			enabled: true,
		},
		{
			name: "ITDOG",
			url: "https://www.itdog.cn/",
			description:
				"在线 Ping、TCPing、网站测速、HTTP 测速、路由追踪、DNS 查询等网络工具",
			category: "测试数据",
			icon: favicon("itdog.cn"),
			enabled: true,
		},
		// 图片
		{
			name: "在线图像工具箱",
			url: "https://phototool.cn/",
			description: "在线图片处理工具，支持格式转换、压缩、裁剪、批量下载等功能",
			category: "图片",
			icon: favicon("phototool.cn"),
			enabled: true,
		},
		{
			name: "SauceNAO",
			url: "https://saucenao.com/",
			description: "以图搜图引擎，支持动漫插画、同人图来源查找",
			category: "图片",
			icon: favicon("saucenao.com"),
			enabled: true,
		},
		{
			name: "StarDots",
			url: "https://dashboard.stardots.io/?lang=zh",
			description: "一站式图片托管与 CDN 加速平台，支持图片管理、转换与分发",
			category: "图片",
			icon: favicon("stardots.io"),
			enabled: true,
		},
		// AI 聊天
		{
			name: "豆包",
			url: "https://www.doubao.com/",
			description: "字节跳动旗下 AI 助手，支持对话、写作、翻译、代码等多种能力",
			category: "AI 聊天",
			icon: favicon("doubao.com"),
			enabled: true,
		},
		{
			name: "ChatGPT",
			url: "https://chatgpt.com/",
			description: "OpenAI 开发的对话式 AI，支持写作、编程、分析等多种任务",
			category: "AI 聊天",
			icon: favicon("chatgpt.com"),
			enabled: true,
		},
		{
			name: "Claude",
			url: "https://claude.ai/",
			description: "Anthropic 开发的 AI 助手，擅长长文本理解、代码与深度分析",
			category: "AI 聊天",
			icon: favicon("claude.ai"),
			enabled: true,
		},
		{
			name: "Gemini",
			url: "https://gemini.google.com/",
			description: "Google 推出的多模态 AI，支持文本、图片理解与代码生成",
			category: "AI 聊天",
			icon: favicon("gemini.google.com"),
			enabled: true,
		},
		{
			name: "Grok",
			url: "https://grok.com/",
			description: "xAI 开发的 AI 助手，支持实时搜索、图像生成与深度推理",
			category: "AI 聊天",
			icon: favicon("grok.com"),
			enabled: true,
		},
		// AI
		{
			name: "Artificial Analysis",
			url: "https://artificialanalysis.ai/?intelligence-category=reasoning-vs-non-reasoning",
			description: "AI 模型推理能力对比分析平台，深入研究推理与非推理模型差异",
			category: "AI",
			icon: favicon("artificialanalysis.ai"),
			enabled: true,
		},
		{
			name: "AI Arena",
			url: "https://arena.ai/leaderboard",
			description: "AI 模型竞技排行榜，对比不同大模型的综合能力",
			category: "AI",
			icon: favicon("arena.ai"),
			enabled: true,
		},
		{
			name: "ModelScope 魔搭社区",
			url: "https://www.modelscope.cn/",
			description: "阿里达摩院开源模型社区，提供海量 AI 模型与推理服务",
			category: "AI",
			icon: favicon("modelscope.cn"),
			enabled: true,
		},
		{
			name: "Skills Marketplace",
			url: "https://skillsmp.com/",
			description: "AI 技能市场，发现和分享 AI 工具与自动化工作流",
			category: "AI",
			icon: favicon("skillsmp.com"),
			enabled: true,
		},
		{
			name: "PromptPilot",
			url: "https://promptpilot.volcengine.com/",
			description: "火山引擎推出的 Prompt 优化工具，提升大模型输出质量",
			category: "AI",
			icon: favicon("volcengine.com"),
			enabled: true,
		},
		{
			name: "ACGN AI 资源站",
			url: "https://res.acgnai.top/",
			description: "ACGN AI 资源聚合平台，提供模型下载、工具推荐与教程分享",
			category: "AI",
			icon: favicon("acgnai.top"),
			enabled: true,
		},
		{
			name: "Oblivion Image Gallery",
			url: "https://image.oblivionis.net/gallery",
			description: "AI 生成图像画廊，展示高质量人工智能艺术作品",
			category: "AI",
			icon: favicon("oblivionis.net"),
			enabled: true,
		},
		{
			name: "Figma",
			url: "https://www.figma.com/",
			description: "在线 UI/UX 设计协作工具，支持 AI 辅助设计功能",
			category: "AI",
			icon: favicon("figma.com"),
			enabled: true,
		},
		{
			name: "Google AI Studio",
			url: "https://aistudio.google.com/",
			description:
				"Google 官方 AI 开发平台，支持 Chat/Build/Stream 三模式，可快速原型化 Gemini 应用",
			category: "AI",
			icon: favicon("aistudio.google.com"),
			enabled: true,
		},
		{
			name: "Google Stitch",
			url: "https://stitch.withgoogle.com/",
			description:
				"Google Labs 推出的 AI 原生 UI 设计工具，用文字或图片生成界面并导出代码",
			category: "AI",
			icon: favicon("withgoogle.com"),
			enabled: true,
		},
		{
			name: "Ollama",
			url: "https://ollama.com/",
			description:
				"本地运行大语言模型的轻量框架，支持一键部署 Llama、Qwen 等开源模型",
			category: "AI",
			icon: favicon("ollama.com"),
			enabled: true,
		},
		// BOT
		{
			name: "NapCat",
			url: "https://napneko.github.io/",
			description: "基于 NTQQ 的 QQ 机器人框架，支持插件扩展与多协议接入",
			category: "BOT",
			icon: favicon("napneko.github.io"),
			enabled: true,
		},
		{
			name: "AstrBot",
			url: "https://astrbot.app/",
			description: "多平台聊天机器人框架，支持 QQ、Discord、Telegram 等",
			category: "BOT",
			icon: favicon("astrbot.app"),
			enabled: true,
		},
		{
			name: "Mai-bot",
			url: "https://docs.mai-mai.org/",
			description: "音乐游戏 MaiMai 相关机器人，支持查分、排位等功能",
			category: "BOT",
			icon: favicon("mai-mai.org"),
			enabled: true,
		},
		{
			name: "NoneBot",
			url: "https://nonebot.dev/docs/",
			description: "Python 异步机器人框架，支持多平台适配器与插件生态",
			category: "BOT",
			icon: favicon("nonebot.dev"),
			enabled: true,
		},
		{
			name: "LLBot",
			url: "https://github.com/LLOneBot/LuckyLilliaBot",
			description: "基于 NTQQ 的 QQ 机器人框架，轻量高效，支持 OneBot 协议",
			category: "BOT",
			icon: favicon("github.com"),
			enabled: true,
		},
		// UI 组件库
		{
			name: "Awwwards",
			url: "https://www.awwwards.com/",
			description: "全球最佳网页设计作品评选平台，汇集创意灵感与设计趋势",
			category: "UI 组件库",
			icon: favicon("awwwards.com"),
			enabled: true,
		},
		{
			name: "shadcn/ui",
			url: "https://ui.shadcn.com/",
			description: "优雅的 React 组件集合，基于 Radix UI 和 Tailwind CSS",
			category: "UI 组件库",
			icon: favicon("shadcn.com"),
			enabled: true,
		},
		{
			name: "HeroUI",
			url: "https://heroui.com/",
			description: "高性能 React UI 组件库，基于 Tailwind 和 Tailwind Variants",
			category: "UI 组件库",
			icon: favicon("heroui.com"),
			enabled: true,
		},
		{
			name: "Uiverse",
			url: "https://uiverse.io/",
			description: "社区驱动的开源 UI 元素库，提供按钮、输入框、卡片等精美组件",
			category: "UI 组件库",
			icon: favicon("uiverse.io"),
			enabled: true,
		},
		{
			name: "CodePen",
			url: "https://codepen.io/",
			description: "前端演示平台，可实时编写和分享 HTML/CSS/JS 代码片段",
			category: "UI 组件库",
			icon: favicon("codepen.io"),
			enabled: true,
		},
		{
			name: "React Bits",
			url: "https://www.reactbits.dev/",
			description: "React 组件与 Hook 精选集合，实用且易集成",
			category: "UI 组件库",
			icon: favicon("reactbits.dev"),
			enabled: true,
		},
		{
			name: "Magic UI",
			url: "https://magicui.design/",
			description: "精美动画组件库，提供可复制粘贴的 UI 动效组件",
			category: "UI 组件库",
			icon: favicon("magicui.design"),
			enabled: true,
		},
		{
			name: "Aceternity UI",
			url: "https://ui.aceternity.com/",
			description: "现代化 React 动画组件库，视觉效果出色的开源组件集合",
			category: "UI 组件库",
			icon: favicon("aceternity.com"),
			enabled: true,
		},
		{
			name: "Iconify",
			url: "https://iconify.design/",
			description:
				"统一图标框架，提供 200,000+ 图标，涵盖 100+ 图标集，支持按需加载",
			category: "UI 组件库",
			icon: favicon("iconify.design"),
			enabled: true,
		},
		{
			name: "Sketchfab",
			url: "https://sketchfab.com/",
			description: "全球最大的 3D 模型展示与分享平台，支持在线预览和免费下载",
			category: "UI 组件库",
			icon: favicon("sketchfab.com"),
			enabled: true,
		},
		// 知识库 / 学习
		{
			name: "Java 全栈知识体系",
			url: "https://pdai.tech/",
			description:
				"涵盖 Java 核心、并发、JVM、框架、数据库、架构等全栈知识体系",
			category: "知识库",
			icon: favicon("pdai.tech"),
			enabled: true,
		},
		{
			name: "JavaGuide",
			url: "https://javaguide.cn/",
			description:
				"Java 学习 + 面试指南，涵盖 Java 基础、集合、并发、JVM、Spring 等核心知识",
			category: "知识库",
			icon: favicon("javaguide.cn"),
			enabled: true,
		},
		{
			name: "异常教程",
			url: "https://www.exception.site/",
			description:
				"提供 IDEA、PyCharm、WebStorm 等 JetBrains 系列 IDE 激活码与安装教程",
			category: "知识库",
			icon: favicon("exception.site"),
			enabled: true,
		},
		{
			name: "力扣 LeetCode",
			url: "https://leetcode.cn/",
			description: "全球极客挚爱的技术成长平台，海量算法题库、面试题与竞赛",
			category: "知识库",
			icon: favicon("leetcode.cn"),
			enabled: true,
		},
		{
			name: "牛客网",
			url: "https://www.nowcoder.com/",
			description:
				"IT 求职备考与技术学习平台，提供笔试、面试题库与在线编程练习",
			category: "知识库",
			icon: favicon("nowcoder.com"),
			enabled: true,
		},
		// 动漫&漫画
		{
			name: "AGE 动漫",
			url: "https://www.agedm.io/update",
			description: "免费动漫资源聚合站，提供高清动漫在线观看与更新推送",
			category: "动漫&漫画",
			icon: favicon("agedm.io"),
			enabled: true,
		},
		{
			name: "ManhwaTop",
			url: "https://manhwatop.com/",
			description: "韩漫/漫画阅读平台，热门连载与完结漫画资源",
			category: "动漫&漫画",
			icon: favicon("manhwatop.com"),
			enabled: true,
		},
		// API
		{
			name: "Zerochan",
			url: "https://www.zerochan.net/",
			description: "大型动漫图片数据库，支持按角色、作品分类搜索",
			category: "API",
			icon: favicon("zerochan.net"),
			enabled: true,
		},
		{
			name: "阿里云API市场",
			url: "https://market.aliyun.com/",
			description: "阿里云提供的API交易平台，涵盖天气、短信、物流等各类服务",
			category: "API",
			icon: favicon("aliyun.com"),
			enabled: true,
		},
		{
			name: "高德地图API",
			url: "https://lbs.amap.com/",
			description: "高德地图开放平台，提供地图、定位、导航等地理服务API",
			category: "API",
			icon: favicon("amap.com"),
			enabled: true,
		},
		{
			name: "聚合数据",
			url: "https://www.juhe.cn/",
			description: "国内领先的数据服务平台，提供短信、物流、新闻等多种API",
			category: "API",
			icon: favicon("juhe.cn"),
			enabled: true,
		},
		{
			name: "有道翻译API",
			url: "https://ai.youdao.com/",
			description: "网易有道提供的翻译API服务，支持多语言互译",
			category: "API",
			icon: favicon("youdao.com"),
			enabled: true,
		},
		{
			name: "Tavily",
			url: "https://app.tavily.com/home",
			description: "AI 优化的搜索引擎 API，为大模型提供实时网页检索能力",
			category: "API",
			icon: favicon("tavily.com"),
			enabled: true,
		},
		// 其他
		{
			name: "PatorJK",
			url: "https://patorjk.com/",
			description: "在线 ASCII 艺术字生成器及其他实用小工具集合",
			category: "其他",
			icon: favicon("patorjk.com"),
			enabled: true,
		},
	],

	// API 分类（可选，留空则自动生成）
	categories: [],
};
